version: "3.9"
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project2
    volumes:
      - data:/var/lib/mysql
volumes:
  data:
